# Generated by Django 2.0.13 on 2021-06-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caosnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_caosnews', models.TextField()),
                ('genero_caosnews', models.TextField()),
            ],
        ),
    ]
