# Generated by Django 2.0.13 on 2021-06-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caosnews',
            old_name='genero_caosnews',
            new_name='apellido_caosnews',
        ),
    ]
