# Generated by Django 2.0.13 on 2021-06-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0002_auto_20210610_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnews',
            name='edad_caosnews',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
