# Generated by Django 2.0.13 on 2021-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0004_remove_caosnews_edad_caosnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnews',
            name='edad_caosnews',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
