# Generated by Django 2.0.13 on 2021-06-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0005_caosnews_edad_caosnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caosnews',
            old_name='edad_caosnews',
            new_name='con_contraseña_caosnews',
        ),
        migrations.AddField(
            model_name='caosnews',
            name='contraseña_caosnews',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caosnews',
            name='correo_caosnews',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
