# Generated by Django 3.2.4 on 2021-07-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0006_auto_20210613_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caosnews',
            name='apellido_caosnews',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caosnews',
            name='con_contraseña_caosnews',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caosnews',
            name='contraseña_caosnews',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caosnews',
            name='correo_caosnews',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='caosnews',
            name='nombre_caosnews',
            field=models.CharField(max_length=50),
        ),
    ]
