# Generated by Django 3.2.4 on 2021-07-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0007_auto_20210705_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='corta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiste', models.CharField(max_length=300)),
                ('resp', models.CharField(max_length=300)),
            ],
        ),
    ]
